import { lstat, readdir, rm } from "node:fs/promises";
import { join, resolve } from "node:path";
import type { CacheEntry } from "../shared/contracts";
import { errorMessage, isInside, isMissing, pathSize } from "./fsutil";
import { runningJob } from "./jobs";
import { editorsForProject, forgetRunningEditors } from "./processes";
import { requireProject } from "./project";

type CatalogEntry = Omit<CacheEntry, "bytes" | "exists">;

/** Everything here is regenerated by Unity or the IDE. Assets, Packages, ProjectSettings, and UserSettings are never listed. */
export const CACHE_CATALOG: readonly CatalogEntry[] = [
  { id: "temp", label: "Temp", paths: ["Temp"], level: "light", description: "Arquivos temporários do Editor; recriados ao abrir o projeto." },
  { id: "obj", label: "obj", paths: ["obj"], level: "light", description: "Saída intermediária de compilação do IDE." },
  { id: "bee", label: "Bee (build/compilação)", paths: ["Library/Bee"], level: "light", description: "Cache do pipeline de compilação e build; o Unity recompila na próxima abertura." },
  { id: "script-assemblies", label: "ScriptAssemblies", paths: ["Library/ScriptAssemblies"], level: "light", description: "DLLs dos scripts; força uma recompilação limpa (resolve erros de compilação fantasmas)." },
  { id: "shader-cache", label: "Shader cache", paths: ["Library/ShaderCache", "Library/ShaderCache.db"], level: "light", description: "Variantes de shader compiladas; recompiladas sob demanda." },
  { id: "burst", label: "Burst cache", paths: ["Library/BurstCache"], level: "light", description: "Código nativo gerado pelo Burst." },
  { id: "il2cpp", label: "IL2CPP cache", paths: ["Library/Il2cppBuildCache"], level: "light", description: "Cache de builds IL2CPP." },
  { id: "logs", label: "Logs", paths: ["Logs"], level: "light", description: "Logs do Editor, do Package Manager e dos builds feitos pelo Paseo." },
  { id: "ide", label: "Projetos do IDE", paths: ["*.csproj", "*.sln", "*.slnx"], level: "light", description: "Regenerados pelo Unity (Assets → Open C# Project)." },
  { id: "package-cache", label: "PackageCache", paths: ["Library/PackageCache"], level: "full", description: "Pacotes resolvidos; baixados de novo na próxima abertura (precisa de rede)." },
  { id: "library", label: "Library inteira", paths: ["Library"], level: "full", description: "Reimporta todos os assets na próxima abertura; pode levar muitos minutos." },
];

export async function scanCache(projectPath: string): Promise<{ entries: CacheEntry[]; editorOpen: boolean }> {
  const project = await requireProject(projectPath);
  const [entries, holders] = await Promise.all([
    Promise.all(
      CACHE_CATALOG.map(async (entry): Promise<CacheEntry> => {
        const paths = await expandPaths(project.path, entry.paths);
        const sizes = await Promise.all(paths.map((path) => pathSize(join(project.path, path))));
        return { ...entry, bytes: sizes.reduce((total, size) => total + size, 0), exists: paths.length > 0 };
      }),
    ),
    editorsForProject(project.path),
  ]);
  return { entries, editorOpen: holders.length > 0 };
}

export async function cleanCache(projectPath: string, ids: readonly string[]) {
  const project = await requireProject(projectPath);
  const holders = await editorsForProject(project.path);
  if (holders.length > 0) throw new Error(`Feche o Unity Editor de ${project.name} antes de limpar o cache (PID ${holders.map((holder) => holder.pid).join(", ")}).`);
  const busy = runningJob(project.path);
  if (busy !== null) throw new Error(`Aguarde a tarefa em andamento terminar: ${busy.job.title}.`);

  const selected = CACHE_CATALOG.filter((entry) => ids.includes(entry.id));
  if (selected.length !== ids.length) throw new Error(`Itens de cache desconhecidos: ${ids.filter((id) => !CACHE_CATALOG.some((entry) => entry.id === id)).join(", ")}`);
  const relativePaths = dropNested((await Promise.all(selected.map((entry) => expandPaths(project.path, entry.paths)))).flat());

  let freedBytes = 0;
  const removed: string[] = [];
  const skipped: { path: string; reason: string }[] = [];
  for (const relativePath of relativePaths) {
    const absolute = resolve(project.path, relativePath);
    if (absolute === resolve(project.path) || !isInside(project.path, absolute)) {
      skipped.push({ path: relativePath, reason: "fora do projeto" });
      continue;
    }
    try {
      const info = await lstat(absolute);
      if (info.isSymbolicLink()) {
        skipped.push({ path: relativePath, reason: "é um link simbólico; não foi seguido" });
        continue;
      }
      const size = await pathSize(absolute);
      await rm(absolute, { recursive: true, force: true, maxRetries: 2 });
      freedBytes += size;
      removed.push(relativePath);
    } catch (error) {
      if (!isMissing(error)) skipped.push({ path: relativePath, reason: errorMessage(error) });
    }
  }
  forgetRunningEditors();
  return { freedBytes, removed, skipped };
}

/** Expands root-level `*.ext` patterns and keeps only paths that exist. */
async function expandPaths(projectPath: string, patterns: readonly string[]): Promise<string[]> {
  const paths: string[] = [];
  let rootEntries: string[] | null = null;
  for (const pattern of patterns) {
    if (pattern.startsWith("*.")) {
      rootEntries ??= await readdir(projectPath);
      const extension = pattern.slice(1);
      paths.push(...rootEntries.filter((name) => name.endsWith(extension)));
      continue;
    }
    try {
      await lstat(join(projectPath, pattern));
      paths.push(pattern);
    } catch (error) {
      if (!isMissing(error)) throw error;
    }
  }
  return paths;
}

/** Selecting `Library` already covers `Library/Bee`; drop the nested entry so it is not counted twice. */
export function dropNested(paths: readonly string[]): string[] {
  const unique = [...new Set(paths)].sort((left, right) => left.length - right.length);
  return unique.filter((path, index) => !unique.slice(0, index).some((parent) => path.startsWith(`${parent}/`)));
}
